version: '3.9'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    # container_name: es01
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./.idea/elasticsearch/data:/usr/share/elasticsearch/data
    # ports:
      # - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.0
    depends_on:
      - es01
    # container_name: kibana
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_HOSTS: http://es01:9200
      XPACK_SECURITY_ENABLED: "false"
      XPACK_GRAPH_ENABLED: "false"
      XPACK_ML_ENABLED: "false"
      XPACK_REPORTING_ENABLED: "false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 5601:5601
  consumer:
    image: python:3.10.0a5-alpine3.13
    depends_on:
      - es01
      - kibana
    env_file:
      - ./.idea/consumer/variables.env
    volumes:
      - ./consumer:/srv
    entrypoint: ["sh", "/srv/entrypoint.sh"]
