version: '3.8'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    # container_name: es01
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    volumes:
      - ./.idea/elasticsearch/data:/usr/share/elasticsearch/data
    # ports:
      # - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.0
    depends_on:
      - es01
    # container_name: kibana
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_HOSTS: http://es01:9200
      XPACK_SECURITY_ENABLED: "false"
      XPACK_GRAPH_ENABLED: "false"
      XPACK_ML_ENABLED: "false"
      XPACK_REPORTING_ENABLED: "false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 256m
    ports:
      - 5601:5601
  redis:
    image: redis:6.0.10-alpine
    # ports:
      # - 6379:6379
  consumer:
    build: ./consumer
    image: stock-advisor-base
    depends_on:
      - redis
    env_file:
      - ./.idea/consumer/variables.env
  worker1:
    image: stock-advisor-base
    depends_on:
      - redis
    env_file:
      - ./.idea/consumer/variables.env
    entrypoint: ["celery", "-A", "pull", "worker", "--logfile=/dev/null"]
  worker2:
    image: stock-advisor-base
    depends_on:
      - redis
    env_file:
      - ./.idea/consumer/variables.env
    entrypoint: ["celery", "-A", "pull", "worker", "--logfile=/dev/null"]
